### ISSUE TITLE
roslaunch prometheus_gazebo sitl_number_detection.launch    error

### ISSUE THREAD

**Issue by imposin** [amov-lab/Prometheus#166]
![2021-10-11 09-35-45 的屏幕截图](https://user-images.githubusercontent.com/82153531/136721621-ce6592d9-1b6e-431c-8c66-331d4e8dded5.png)

**Comment by imposin** [comment]
可以启动 控制模块  这个是单系统promethues镜像

**Comment by potato77** [comment]
> 可以启动 控制模块 这个是单系统promethues镜像

镜像就不清楚了

**Comment by Handsome-B** [comment]
为啥我还有这个问题呀。。。

**Comment by Handsome-B** [comment]
> #173 已经修复了，请git pull更新一下

我用的最新的可是为啥还有这个问题呀

**Comment by imposin** [comment]
> 为啥我还有这个问题呀。。。

我的 git pull 后就好了

**Comment by Handsome-B** [comment]
我当时遇到的问题是：

然后我的解决方法是：

rosdep update

sudo pip install -U rosdep



------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "amov-lab/Prometheus"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年12月2日(星期四) 上午10:41
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [amov-lab/Prometheus] roslaunch prometheus_gazebo sitl_number_detection.launch    error (#166)





   
#173 已经修复了，请git pull更新一下
  
我用的最新的可是为啥还有这个问题呀
  
我也是这样的 还有第一个错误
 
—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
